export const taskConstants = { 
    GET_TASK_REQUEST: 'GET_TASK_REQUEST',
    GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
    GET_TASK_FAILURE: 'GET_TASK_FAILURE',

    ADD_TASK_REQUEST: 'ADD_TASK_REQUEST',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_FAILURE: 'ADD_TASK_FAILURE',

    EDIT_TASK_REQUEST: 'EDIT_TASK_REQUEST',
    EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCESS',
    EDIT_TASK_FAILURE: 'EDIT_TASK_FAILURE',

    REMOVE_TASK_REQUEST: 'REMOVE_TASK_REQUEST',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
    REMOVE_TASK_FAILURE: 'REMOVE_TASK_FAILURE',

    SEARCH_TASKS_REQUEST: 'SEARCH_TASKS_REQUEST',
    SEARCH_TASKS_SUCCESS: 'SEARCH_TASKS_SUCCESS',
    SEARCH_TASKS_FAILURE: 'SEARCH_TASKS_FAILURE',

    CHANGE_STATUS_REQUEST: 'CHANGE_STATUS_REQUEST',
    CHANGE_STATUS_SUCCESS: 'CHANGE_STATUS_SUCCESS',
    CHANGE_STATUS_FAILURE: 'CHANGE_STATUS_FAILURE',
    
    OPEN_MODAL_ADD_EDIT: 'OPEN_MODAL_ADD_EDIT',
    CLOSE_MODAL_ADD_EDIT: 'CLOSE_MODAL_ADD_EDIT',
};